export const theatres = [
  {
    name: 'PVR INOX Nexus',
    location: 'Koramangala, Bengaluru, Karnataka',
    totalScreens: 8,
  },
  {
    name: 'INOX Nariman Point',
    location: 'Marine Drive, Mumbai, Maharashtra',
    totalScreens: 6,
  },
  {
    name: 'Sathyam Cinemas',
    location: 'Royapettah, Chennai, Tamil Nadu',
    totalScreens: 7,
  },
  {
    name: 'Nandan Cinema',
    location: 'Rabindra Sadan, Kolkata, West Bengal',
    totalScreens: 5,
  },
  {
    name: 'PVR Lulu Mall',
    location: 'Edappally, Kochi, Kerala',
    totalScreens: 9,
  },
  {
    name: 'AMB Cinemas',
    location: 'Gachibowli, Hyderabad, Telangana',
    totalScreens: 10,
  },
  {
    name: 'Asian Cinemas CMR',
    location: 'Labbipet, Vijayawada, Andhra Pradesh',
    totalScreens: 6,
  },
  {
    name: 'Raj Mandir Cinema',
    location: 'Bhagwan Das Road, Jaipur, Rajasthan',
    totalScreens: 4,
  },
  {
    name: 'PVR Sahara Mall',
    location: 'MG Road, Gurugram, Haryana',
    totalScreens: 7,
  },
  {
    name: 'Wave Cinemas',
    location: 'Gomti Nagar, Lucknow, Uttar Pradesh',
    totalScreens: 8,
  },
  {
    name: 'Cinepolis Treasure Island',
    location: 'CG Road, Ahmedabad, Gujarat',
    totalScreens: 6,
  },
  {
    name: 'INOX Aashima Mall',
    location: 'MP Nagar, Bhopal, Madhya Pradesh',
    totalScreens: 5,
  },
  {
    name: 'PVR Forum Mall',
    location: 'Elgin Road, Ranchi, Jharkhand',
    totalScreens: 4,
  },
  {
    name: 'Cinepolis Boring Road',
    location: 'Boring Road, Patna, Bihar',
    totalScreens: 5,
  },
  {
    name: 'INOX City Centre',
    location: 'GS Road, Guwahati, Assam',
    totalScreens: 4,
  },
  {
    name: 'PVR Magneto Mall',
    location: 'Labhandi, Raipur, Chhattisgarh',
    totalScreens: 5,
  },
  {
    name: 'INOX Panjim',
    location: 'DB Marg, Panaji, Goa',
    totalScreens: 3,
  },
  {
    name: 'Cinepolis VR Punjab',
    location: 'Sahibzada Ajit Singh Nagar, Punjab',
    totalScreens: 7,
  },
  {
    name: 'PVR Esplanade',
    location: 'Sahid Nagar, Bhubaneswar, Odisha',
    totalScreens: 5,
  },
  {
    name: 'INOX Regenta',
    location: 'Rajpur Road, Dehradun, Uttarakhand',
    totalScreens: 4,
  },
  {
    name: 'PVR Mall Road',
    location: 'Mall Road, Shimla, Himachal Pradesh',
    totalScreens: 3,
  },
  {
    name: 'INOX Polo Towers',
    location: 'MG Marg, Gangtok, Sikkim',
    totalScreens: 2,
  },
  {
    name: 'Gold Cinema Imphal',
    location: 'Thangal Bazaar, Imphal, Manipur',
    totalScreens: 2,
  },
  {
    name: 'Bijou Cinema',
    location: 'Police Bazaar, Shillong, Meghalaya',
    totalScreens: 2,
  },
  {
    name: 'Zoram Cinema',
    location: 'Zarkawt, Aizawl, Mizoram',
    totalScreens: 2,
  },
  {
    name: 'Nagaland Cinema Hall',
    location: 'Midland, Dimapur, Nagaland',
    totalScreens: 2,
  },
  {
    name: 'Rupasi Cinema',
    location: 'Agartala, Tripura',
    totalScreens: 2,
  },
  {
    name: 'Cineplex Itanagar',
    location: 'Ganga Market, Itanagar, Arunachal Pradesh',
    totalScreens: 2,
  },
];

export const movies = [
  {
    title: 'The Last Horizon',
    genre: 'Sci-Fi',
    durationMinutes: 142,
    rating: 'PG-13',
    posterUrl: null,
  },
  {
    title: 'Midnight in Havana',
    genre: 'Drama',
    durationMinutes: 118,
    rating: 'R',
    posterUrl: null,
  },
  {
    title: 'Turbo Rush',
    genre: 'Action',
    durationMinutes: 126,
    rating: 'PG-13',
    posterUrl: null,
  },
  {
    title: 'The Enchanted Garden',
    genre: 'Animation',
    durationMinutes: 98,
    rating: 'G',
    posterUrl: null,
  },
  {
    title: 'Code Red',
    genre: 'Thriller',
    durationMinutes: 110,
    rating: 'R',
    posterUrl: null,
  },
  {
    title: 'Love in Transit',
    genre: 'Romance',
    durationMinutes: 105,
    rating: 'PG-13',
    posterUrl: null,
  },
  {
    title: 'Echoes of Tomorrow',
    genre: 'Sci-Fi',
    durationMinutes: 135,
    rating: 'PG-13',
    posterUrl: null,
  },
];

export interface ShowtimeSeed {
  theatreIndex: number;
  movieIndex: number;
  screen: string;
  startTime: string;
  price: number;
}

export const showtimes: ShowtimeSeed[] = [
  {
    theatreIndex: 0,
    movieIndex: 0,
    screen: '1',
    startTime: '2026-06-20T14:00:00Z',
    price: 14.99,
  },
  {
    theatreIndex: 0,
    movieIndex: 1,
    screen: '2',
    startTime: '2026-06-20T16:30:00Z',
    price: 12.99,
  },
  {
    theatreIndex: 0,
    movieIndex: 3,
    screen: '3',
    startTime: '2026-06-20T11:00:00Z',
    price: 10.99,
  },
  {
    theatreIndex: 1,
    movieIndex: 0,
    screen: '1',
    startTime: '2026-06-20T19:00:00Z',
    price: 18.99,
  },
  {
    theatreIndex: 1,
    movieIndex: 2,
    screen: '2',
    startTime: '2026-06-20T21:00:00Z',
    price: 17.99,
  },
  {
    theatreIndex: 2,
    movieIndex: 4,
    screen: '1',
    startTime: '2026-06-20T15:00:00Z',
    price: 13.99,
  },
  {
    theatreIndex: 2,
    movieIndex: 5,
    screen: '3',
    startTime: '2026-06-20T18:00:00Z',
    price: 12.99,
  },
  {
    theatreIndex: 2,
    movieIndex: 6,
    screen: '5',
    startTime: '2026-06-20T20:30:00Z',
    price: 14.99,
  },
  {
    theatreIndex: 3,
    movieIndex: 1,
    screen: '1',
    startTime: '2026-06-20T13:00:00Z',
    price: 11.99,
  },
  {
    theatreIndex: 3,
    movieIndex: 2,
    screen: '2',
    startTime: '2026-06-20T17:00:00Z',
    price: 12.99,
  },
  {
    theatreIndex: 4,
    movieIndex: 3,
    screen: '1',
    startTime: '2026-06-20T10:00:00Z',
    price: 9.99,
  },
  {
    theatreIndex: 4,
    movieIndex: 6,
    screen: '4',
    startTime: '2026-06-20T22:00:00Z',
    price: 15.99,
  },
  // Theatre 5 – AMB Cinemas, Hyderabad
  {
    theatreIndex: 5,
    movieIndex: 0,
    screen: '1',
    startTime: '2026-06-24T14:00:00Z',
    price: 16.99,
  },
  {
    theatreIndex: 5,
    movieIndex: 3,
    screen: '3',
    startTime: '2026-06-24T17:30:00Z',
    price: 14.99,
  },
  {
    theatreIndex: 5,
    movieIndex: 5,
    screen: '5',
    startTime: '2026-06-24T20:00:00Z',
    price: 17.99,
  },
  // Theatre 6 – Asian Cinemas CMR, Vijayawada
  {
    theatreIndex: 6,
    movieIndex: 1,
    screen: '1',
    startTime: '2026-06-24T13:00:00Z',
    price: 11.99,
  },
  {
    theatreIndex: 6,
    movieIndex: 4,
    screen: '2',
    startTime: '2026-06-24T18:00:00Z',
    price: 12.99,
  },
  // Theatre 7 – Raj Mandir Cinema, Jaipur
  {
    theatreIndex: 7,
    movieIndex: 2,
    screen: '1',
    startTime: '2026-06-24T15:00:00Z',
    price: 13.99,
  },
  {
    theatreIndex: 7,
    movieIndex: 6,
    screen: '2',
    startTime: '2026-06-24T19:30:00Z',
    price: 14.99,
  },
  // Theatre 8 – PVR Sahara Mall, Gurugram
  {
    theatreIndex: 8,
    movieIndex: 0,
    screen: '1',
    startTime: '2026-06-24T11:00:00Z',
    price: 15.99,
  },
  {
    theatreIndex: 8,
    movieIndex: 3,
    screen: '3',
    startTime: '2026-06-24T14:30:00Z',
    price: 13.99,
  },
  {
    theatreIndex: 8,
    movieIndex: 5,
    screen: '5',
    startTime: '2026-06-24T21:00:00Z',
    price: 16.99,
  },
  // Theatre 9 – Wave Cinemas, Lucknow
  {
    theatreIndex: 9,
    movieIndex: 1,
    screen: '1',
    startTime: '2026-06-24T12:00:00Z',
    price: 11.99,
  },
  {
    theatreIndex: 9,
    movieIndex: 4,
    screen: '2',
    startTime: '2026-06-24T16:00:00Z',
    price: 12.99,
  },
  {
    theatreIndex: 9,
    movieIndex: 6,
    screen: '4',
    startTime: '2026-06-24T20:30:00Z',
    price: 13.99,
  },
  // Theatre 10 – Cinepolis Treasure Island, Ahmedabad
  {
    theatreIndex: 10,
    movieIndex: 0,
    screen: '1',
    startTime: '2026-06-24T14:00:00Z',
    price: 14.99,
  },
  {
    theatreIndex: 10,
    movieIndex: 2,
    screen: '3',
    startTime: '2026-06-24T18:30:00Z',
    price: 15.99,
  },
  // Theatre 11 – INOX Aashima Mall, Bhopal
  {
    theatreIndex: 11,
    movieIndex: 3,
    screen: '1',
    startTime: '2026-06-24T10:30:00Z',
    price: 9.99,
  },
  {
    theatreIndex: 11,
    movieIndex: 5,
    screen: '2',
    startTime: '2026-06-24T17:00:00Z',
    price: 12.99,
  },
  // Theatre 12 – PVR Forum Mall, Ranchi
  {
    theatreIndex: 12,
    movieIndex: 1,
    screen: '1',
    startTime: '2026-06-24T13:30:00Z',
    price: 11.99,
  },
  {
    theatreIndex: 12,
    movieIndex: 6,
    screen: '2',
    startTime: '2026-06-24T19:00:00Z',
    price: 13.99,
  },
  // Theatre 13 – Cinepolis Boring Road, Patna
  {
    theatreIndex: 13,
    movieIndex: 0,
    screen: '1',
    startTime: '2026-06-24T15:00:00Z',
    price: 12.99,
  },
  {
    theatreIndex: 13,
    movieIndex: 4,
    screen: '2',
    startTime: '2026-06-24T20:00:00Z',
    price: 13.99,
  },
  // Theatre 14 – INOX City Centre, Guwahati
  {
    theatreIndex: 14,
    movieIndex: 2,
    screen: '1',
    startTime: '2026-06-24T14:00:00Z',
    price: 12.99,
  },
  {
    theatreIndex: 14,
    movieIndex: 5,
    screen: '2',
    startTime: '2026-06-24T18:30:00Z',
    price: 11.99,
  },
  // Theatre 15 – PVR Magneto Mall, Raipur
  {
    theatreIndex: 15,
    movieIndex: 3,
    screen: '1',
    startTime: '2026-06-24T11:00:00Z',
    price: 10.99,
  },
  {
    theatreIndex: 15,
    movieIndex: 1,
    screen: '3',
    startTime: '2026-06-24T16:30:00Z',
    price: 12.99,
  },
  // Theatre 16 – INOX Panjim, Goa
  {
    theatreIndex: 16,
    movieIndex: 6,
    screen: '1',
    startTime: '2026-06-24T15:30:00Z',
    price: 14.99,
  },
  {
    theatreIndex: 16,
    movieIndex: 0,
    screen: '2',
    startTime: '2026-06-24T19:00:00Z',
    price: 16.99,
  },
  // Theatre 17 – Cinepolis VR Punjab
  {
    theatreIndex: 17,
    movieIndex: 2,
    screen: '1',
    startTime: '2026-06-24T13:00:00Z',
    price: 14.99,
  },
  {
    theatreIndex: 17,
    movieIndex: 4,
    screen: '3',
    startTime: '2026-06-24T17:00:00Z',
    price: 15.99,
  },
  {
    theatreIndex: 17,
    movieIndex: 6,
    screen: '5',
    startTime: '2026-06-24T21:00:00Z',
    price: 16.99,
  },
  // Theatre 18 – PVR Esplanade, Bhubaneswar
  {
    theatreIndex: 18,
    movieIndex: 1,
    screen: '1',
    startTime: '2026-06-24T12:30:00Z',
    price: 11.99,
  },
  {
    theatreIndex: 18,
    movieIndex: 5,
    screen: '2',
    startTime: '2026-06-24T18:00:00Z',
    price: 12.99,
  },
  // Theatre 19 – INOX Regenta, Dehradun
  {
    theatreIndex: 19,
    movieIndex: 0,
    screen: '1',
    startTime: '2026-06-24T14:30:00Z',
    price: 13.99,
  },
  {
    theatreIndex: 19,
    movieIndex: 3,
    screen: '2',
    startTime: '2026-06-24T17:30:00Z',
    price: 11.99,
  },
  // Theatre 20 – PVR Mall Road, Shimla
  {
    theatreIndex: 20,
    movieIndex: 4,
    screen: '1',
    startTime: '2026-06-24T15:00:00Z',
    price: 12.99,
  },
  {
    theatreIndex: 20,
    movieIndex: 6,
    screen: '2',
    startTime: '2026-06-24T19:30:00Z',
    price: 13.99,
  },
  // Theatre 21 – INOX Polo Towers, Gangtok
  {
    theatreIndex: 21,
    movieIndex: 2,
    screen: '1',
    startTime: '2026-06-24T14:00:00Z',
    price: 12.99,
  },
  {
    theatreIndex: 21,
    movieIndex: 5,
    screen: '2',
    startTime: '2026-06-24T18:00:00Z',
    price: 11.99,
  },
  // Theatre 22 – Gold Cinema Imphal
  {
    theatreIndex: 22,
    movieIndex: 0,
    screen: '1',
    startTime: '2026-06-24T13:00:00Z',
    price: 10.99,
  },
  {
    theatreIndex: 22,
    movieIndex: 1,
    screen: '2',
    startTime: '2026-06-24T17:30:00Z',
    price: 11.99,
  },
  // Theatre 23 – Bijou Cinema, Shillong
  {
    theatreIndex: 23,
    movieIndex: 3,
    screen: '1',
    startTime: '2026-06-24T14:30:00Z',
    price: 10.99,
  },
  {
    theatreIndex: 23,
    movieIndex: 4,
    screen: '2',
    startTime: '2026-06-24T19:00:00Z',
    price: 11.99,
  },
  // Theatre 24 – Zoram Cinema, Aizawl
  {
    theatreIndex: 24,
    movieIndex: 6,
    screen: '1',
    startTime: '2026-06-24T15:00:00Z',
    price: 10.99,
  },
  {
    theatreIndex: 24,
    movieIndex: 2,
    screen: '2',
    startTime: '2026-06-24T19:30:00Z',
    price: 11.99,
  },
  // Theatre 25 – Nagaland Cinema Hall, Dimapur
  {
    theatreIndex: 25,
    movieIndex: 5,
    screen: '1',
    startTime: '2026-06-24T13:30:00Z',
    price: 10.99,
  },
  {
    theatreIndex: 25,
    movieIndex: 0,
    screen: '2',
    startTime: '2026-06-24T18:00:00Z',
    price: 11.99,
  },
  // Theatre 26 – Rupasi Cinema, Agartala
  {
    theatreIndex: 26,
    movieIndex: 1,
    screen: '1',
    startTime: '2026-06-24T14:00:00Z',
    price: 10.99,
  },
  {
    theatreIndex: 26,
    movieIndex: 3,
    screen: '2',
    startTime: '2026-06-24T18:30:00Z',
    price: 11.99,
  },
  // Theatre 27 – Cineplex Itanagar
  {
    theatreIndex: 27,
    movieIndex: 4,
    screen: '1',
    startTime: '2026-06-24T15:00:00Z',
    price: 10.99,
  },
  {
    theatreIndex: 27,
    movieIndex: 6,
    screen: '2',
    startTime: '2026-06-24T19:00:00Z',
    price: 11.99,
  },
];

export const menuItems = [
  {
    name: 'Classic Popcorn',
    description: 'Freshly popped buttered popcorn',
    category: 'Snacks',
    size: 'Regular',
    basePrice: 6.99,
  },
  {
    name: 'Nachos Supreme',
    description: 'Crispy tortilla chips with cheese sauce and jalapenos',
    category: 'Snacks',
    size: 'Large',
    basePrice: 8.49,
  },
  {
    name: 'Hot Dog',
    description: 'All-beef frank with mustard and ketchup',
    category: 'Snacks',
    size: null,
    basePrice: 5.99,
  },
  {
    name: 'Pepsi',
    description: 'Chilled Pepsi (500ml)',
    category: 'Beverages',
    size: '500ml',
    basePrice: 3.99,
  },
  {
    name: 'Iced Lemonade',
    description: 'Freshly squeezed lemonade with ice',
    category: 'Beverages',
    size: '350ml',
    basePrice: 4.49,
  },
  {
    name: 'Bottled Water',
    description: 'Still mineral water (500ml)',
    category: 'Beverages',
    size: '500ml',
    basePrice: 2.49,
  },
  {
    name: 'Chocolate Brownie',
    description: 'Warm fudge brownie with chocolate chips',
    category: 'Desserts',
    size: null,
    basePrice: 5.49,
  },
  {
    name: 'Ice Cream Cup',
    description: 'Vanilla and chocolate swirl cup',
    category: 'Desserts',
    size: 'Small',
    basePrice: 4.99,
  },
];

export interface InventorySeed {
  theatreIndex: number;
  menuItemIndex: number;
  quantity: number;
}

export const inventoryItems: InventorySeed[] = [
  { theatreIndex: 0, menuItemIndex: 0, quantity: 50 },
  { theatreIndex: 0, menuItemIndex: 1, quantity: 30 },
  { theatreIndex: 0, menuItemIndex: 2, quantity: 25 },
  { theatreIndex: 0, menuItemIndex: 3, quantity: 80 },
  { theatreIndex: 0, menuItemIndex: 4, quantity: 40 },
  { theatreIndex: 0, menuItemIndex: 5, quantity: 100 },
  { theatreIndex: 0, menuItemIndex: 6, quantity: 20 },
  { theatreIndex: 0, menuItemIndex: 7, quantity: 15 },
  { theatreIndex: 1, menuItemIndex: 0, quantity: 40 },
  { theatreIndex: 1, menuItemIndex: 1, quantity: 20 },
  { theatreIndex: 1, menuItemIndex: 3, quantity: 60 },
  { theatreIndex: 1, menuItemIndex: 5, quantity: 70 },
  { theatreIndex: 1, menuItemIndex: 6, quantity: 15 },
  { theatreIndex: 2, menuItemIndex: 0, quantity: 60 },
  { theatreIndex: 2, menuItemIndex: 2, quantity: 35 },
  { theatreIndex: 2, menuItemIndex: 3, quantity: 90 },
  { theatreIndex: 2, menuItemIndex: 4, quantity: 45 },
  { theatreIndex: 2, menuItemIndex: 7, quantity: 25 },
  { theatreIndex: 3, menuItemIndex: 0, quantity: 45 },
  { theatreIndex: 3, menuItemIndex: 1, quantity: 25 },
  { theatreIndex: 3, menuItemIndex: 3, quantity: 55 },
  { theatreIndex: 3, menuItemIndex: 6, quantity: 10 },
  { theatreIndex: 4, menuItemIndex: 0, quantity: 70 },
  { theatreIndex: 4, menuItemIndex: 1, quantity: 35 },
  { theatreIndex: 4, menuItemIndex: 2, quantity: 30 },
  { theatreIndex: 4, menuItemIndex: 3, quantity: 100 },
  { theatreIndex: 4, menuItemIndex: 4, quantity: 50 },
  { theatreIndex: 4, menuItemIndex: 5, quantity: 120 },
  { theatreIndex: 4, menuItemIndex: 6, quantity: 25 },
  { theatreIndex: 4, menuItemIndex: 7, quantity: 20 },
  // Theatre 5 – AMB Cinemas, Hyderabad (10 screens)
  { theatreIndex: 5, menuItemIndex: 0, quantity: 80 },
  { theatreIndex: 5, menuItemIndex: 1, quantity: 40 },
  { theatreIndex: 5, menuItemIndex: 2, quantity: 35 },
  { theatreIndex: 5, menuItemIndex: 3, quantity: 100 },
  { theatreIndex: 5, menuItemIndex: 4, quantity: 50 },
  { theatreIndex: 5, menuItemIndex: 5, quantity: 120 },
  { theatreIndex: 5, menuItemIndex: 6, quantity: 30 },
  { theatreIndex: 5, menuItemIndex: 7, quantity: 25 },
  // Theatre 6 – Asian Cinemas CMR, Vijayawada (6 screens)
  { theatreIndex: 6, menuItemIndex: 0, quantity: 50 },
  { theatreIndex: 6, menuItemIndex: 1, quantity: 25 },
  { theatreIndex: 6, menuItemIndex: 3, quantity: 70 },
  { theatreIndex: 6, menuItemIndex: 4, quantity: 35 },
  { theatreIndex: 6, menuItemIndex: 5, quantity: 80 },
  { theatreIndex: 6, menuItemIndex: 6, quantity: 15 },
  // Theatre 7 – Raj Mandir Cinema, Jaipur (4 screens)
  { theatreIndex: 7, menuItemIndex: 0, quantity: 40 },
  { theatreIndex: 7, menuItemIndex: 2, quantity: 20 },
  { theatreIndex: 7, menuItemIndex: 3, quantity: 50 },
  { theatreIndex: 7, menuItemIndex: 5, quantity: 60 },
  { theatreIndex: 7, menuItemIndex: 7, quantity: 15 },
  // Theatre 8 – PVR Sahara Mall, Gurugram (7 screens)
  { theatreIndex: 8, menuItemIndex: 0, quantity: 60 },
  { theatreIndex: 8, menuItemIndex: 1, quantity: 30 },
  { theatreIndex: 8, menuItemIndex: 2, quantity: 25 },
  { theatreIndex: 8, menuItemIndex: 3, quantity: 80 },
  { theatreIndex: 8, menuItemIndex: 4, quantity: 40 },
  { theatreIndex: 8, menuItemIndex: 5, quantity: 90 },
  { theatreIndex: 8, menuItemIndex: 6, quantity: 20 },
  { theatreIndex: 8, menuItemIndex: 7, quantity: 18 },
  // Theatre 9 – Wave Cinemas, Lucknow (8 screens)
  { theatreIndex: 9, menuItemIndex: 0, quantity: 55 },
  { theatreIndex: 9, menuItemIndex: 1, quantity: 30 },
  { theatreIndex: 9, menuItemIndex: 2, quantity: 25 },
  { theatreIndex: 9, menuItemIndex: 3, quantity: 75 },
  { theatreIndex: 9, menuItemIndex: 4, quantity: 35 },
  { theatreIndex: 9, menuItemIndex: 5, quantity: 85 },
  { theatreIndex: 9, menuItemIndex: 6, quantity: 20 },
  { theatreIndex: 9, menuItemIndex: 7, quantity: 15 },
  // Theatre 10 – Cinepolis Treasure Island, Ahmedabad (6 screens)
  { theatreIndex: 10, menuItemIndex: 0, quantity: 50 },
  { theatreIndex: 10, menuItemIndex: 1, quantity: 25 },
  { theatreIndex: 10, menuItemIndex: 3, quantity: 65 },
  { theatreIndex: 10, menuItemIndex: 4, quantity: 30 },
  { theatreIndex: 10, menuItemIndex: 5, quantity: 75 },
  { theatreIndex: 10, menuItemIndex: 7, quantity: 15 },
  // Theatre 11 – INOX Aashima Mall, Bhopal (5 screens)
  { theatreIndex: 11, menuItemIndex: 0, quantity: 45 },
  { theatreIndex: 11, menuItemIndex: 2, quantity: 20 },
  { theatreIndex: 11, menuItemIndex: 3, quantity: 55 },
  { theatreIndex: 11, menuItemIndex: 5, quantity: 65 },
  { theatreIndex: 11, menuItemIndex: 6, quantity: 12 },
  // Theatre 12 – PVR Forum Mall, Ranchi (4 screens)
  { theatreIndex: 12, menuItemIndex: 0, quantity: 35 },
  { theatreIndex: 12, menuItemIndex: 1, quantity: 20 },
  { theatreIndex: 12, menuItemIndex: 3, quantity: 50 },
  { theatreIndex: 12, menuItemIndex: 5, quantity: 55 },
  { theatreIndex: 12, menuItemIndex: 7, quantity: 10 },
  // Theatre 13 – Cinepolis Boring Road, Patna (5 screens)
  { theatreIndex: 13, menuItemIndex: 0, quantity: 40 },
  { theatreIndex: 13, menuItemIndex: 2, quantity: 20 },
  { theatreIndex: 13, menuItemIndex: 3, quantity: 55 },
  { theatreIndex: 13, menuItemIndex: 4, quantity: 25 },
  { theatreIndex: 13, menuItemIndex: 5, quantity: 60 },
  { theatreIndex: 13, menuItemIndex: 6, quantity: 12 },
  // Theatre 14 – INOX City Centre, Guwahati (4 screens)
  { theatreIndex: 14, menuItemIndex: 0, quantity: 35 },
  { theatreIndex: 14, menuItemIndex: 1, quantity: 15 },
  { theatreIndex: 14, menuItemIndex: 3, quantity: 45 },
  { theatreIndex: 14, menuItemIndex: 5, quantity: 55 },
  { theatreIndex: 14, menuItemIndex: 6, quantity: 10 },
  // Theatre 15 – PVR Magneto Mall, Raipur (5 screens)
  { theatreIndex: 15, menuItemIndex: 0, quantity: 45 },
  { theatreIndex: 15, menuItemIndex: 1, quantity: 20 },
  { theatreIndex: 15, menuItemIndex: 3, quantity: 60 },
  { theatreIndex: 15, menuItemIndex: 4, quantity: 30 },
  { theatreIndex: 15, menuItemIndex: 5, quantity: 70 },
  { theatreIndex: 15, menuItemIndex: 7, quantity: 12 },
  // Theatre 16 – INOX Panjim, Goa (3 screens)
  { theatreIndex: 16, menuItemIndex: 0, quantity: 30 },
  { theatreIndex: 16, menuItemIndex: 3, quantity: 40 },
  { theatreIndex: 16, menuItemIndex: 4, quantity: 25 },
  { theatreIndex: 16, menuItemIndex: 5, quantity: 50 },
  { theatreIndex: 16, menuItemIndex: 6, quantity: 10 },
  // Theatre 17 – Cinepolis VR Punjab (7 screens)
  { theatreIndex: 17, menuItemIndex: 0, quantity: 60 },
  { theatreIndex: 17, menuItemIndex: 1, quantity: 30 },
  { theatreIndex: 17, menuItemIndex: 2, quantity: 25 },
  { theatreIndex: 17, menuItemIndex: 3, quantity: 80 },
  { theatreIndex: 17, menuItemIndex: 4, quantity: 40 },
  { theatreIndex: 17, menuItemIndex: 5, quantity: 90 },
  { theatreIndex: 17, menuItemIndex: 6, quantity: 20 },
  { theatreIndex: 17, menuItemIndex: 7, quantity: 15 },
  // Theatre 18 – PVR Esplanade, Bhubaneswar (5 screens)
  { theatreIndex: 18, menuItemIndex: 0, quantity: 40 },
  { theatreIndex: 18, menuItemIndex: 2, quantity: 20 },
  { theatreIndex: 18, menuItemIndex: 3, quantity: 55 },
  { theatreIndex: 18, menuItemIndex: 5, quantity: 65 },
  { theatreIndex: 18, menuItemIndex: 6, quantity: 12 },
  // Theatre 19 – INOX Regenta, Dehradun (4 screens)
  { theatreIndex: 19, menuItemIndex: 0, quantity: 35 },
  { theatreIndex: 19, menuItemIndex: 1, quantity: 15 },
  { theatreIndex: 19, menuItemIndex: 3, quantity: 45 },
  { theatreIndex: 19, menuItemIndex: 5, quantity: 55 },
  { theatreIndex: 19, menuItemIndex: 7, quantity: 10 },
  // Theatre 20 – PVR Mall Road, Shimla (3 screens)
  { theatreIndex: 20, menuItemIndex: 0, quantity: 25 },
  { theatreIndex: 20, menuItemIndex: 3, quantity: 35 },
  { theatreIndex: 20, menuItemIndex: 5, quantity: 45 },
  { theatreIndex: 20, menuItemIndex: 6, quantity: 8 },
  // Theatre 21 – INOX Polo Towers, Gangtok (2 screens)
  { theatreIndex: 21, menuItemIndex: 0, quantity: 20 },
  { theatreIndex: 21, menuItemIndex: 3, quantity: 30 },
  { theatreIndex: 21, menuItemIndex: 5, quantity: 40 },
  { theatreIndex: 21, menuItemIndex: 7, quantity: 8 },
  // Theatre 22 – Gold Cinema Imphal (2 screens)
  { theatreIndex: 22, menuItemIndex: 0, quantity: 20 },
  { theatreIndex: 22, menuItemIndex: 2, quantity: 10 },
  { theatreIndex: 22, menuItemIndex: 3, quantity: 30 },
  { theatreIndex: 22, menuItemIndex: 5, quantity: 35 },
  // Theatre 23 – Bijou Cinema, Shillong (2 screens)
  { theatreIndex: 23, menuItemIndex: 0, quantity: 20 },
  { theatreIndex: 23, menuItemIndex: 3, quantity: 30 },
  { theatreIndex: 23, menuItemIndex: 4, quantity: 15 },
  { theatreIndex: 23, menuItemIndex: 5, quantity: 35 },
  // Theatre 24 – Zoram Cinema, Aizawl (2 screens)
  { theatreIndex: 24, menuItemIndex: 0, quantity: 18 },
  { theatreIndex: 24, menuItemIndex: 3, quantity: 25 },
  { theatreIndex: 24, menuItemIndex: 5, quantity: 30 },
  { theatreIndex: 24, menuItemIndex: 6, quantity: 8 },
  // Theatre 25 – Nagaland Cinema Hall, Dimapur (2 screens)
  { theatreIndex: 25, menuItemIndex: 0, quantity: 18 },
  { theatreIndex: 25, menuItemIndex: 2, quantity: 10 },
  { theatreIndex: 25, menuItemIndex: 3, quantity: 25 },
  { theatreIndex: 25, menuItemIndex: 5, quantity: 30 },
  // Theatre 26 – Rupasi Cinema, Agartala (2 screens)
  { theatreIndex: 26, menuItemIndex: 0, quantity: 18 },
  { theatreIndex: 26, menuItemIndex: 3, quantity: 25 },
  { theatreIndex: 26, menuItemIndex: 5, quantity: 30 },
  { theatreIndex: 26, menuItemIndex: 7, quantity: 8 },
  // Theatre 27 – Cineplex Itanagar (2 screens)
  { theatreIndex: 27, menuItemIndex: 0, quantity: 18 },
  { theatreIndex: 27, menuItemIndex: 3, quantity: 25 },
  { theatreIndex: 27, menuItemIndex: 5, quantity: 30 },
  { theatreIndex: 27, menuItemIndex: 6, quantity: 8 },
];
